config/routes.rb
Workspace::Application.routes.draw do
resources :users

get'sign_up'=>'users#new'
get'sign_in'=>'session_user#new'
post'sign_in'=>'session_user#create'
delete 'sign_out' =>'session_user#destroy', as: :sign_out
 root 'static_pages#welcome'
 

end

app/models/user.rb
class User < ActiveRecord::Base
    
 validates :name, presence: true
    validates :email,   presence: true, 
                        format: { with: /\A\S+@\w+\.\w+\z/, 
                            message: 'format is invalid' }
                                
    has_secure_password
    
    validates :password , presence: true,
                          length:{ minimum:6}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/session_user_controller.rb
class SessionUserController < ApplicationController
    
    def new
    
    @user = User.new
    
    end
    
    
    def create 
       
       @user = User.find_by(email: params[:session][:email])
       
       if @user
          if @user.authenticate(params[:session][:password]) 
               session[:user_id] = @user.id
               redirect_to user_path(id: @user.id), notice: 'Successfully Signed In'
            else
                redirect_to sign_in_path, notice: "Incorrect Username/Password"
                
            end
        else
            redirect_to sign_in_path, notice: "User Not found"
        end
    end
    
    
    def destroy
    
        session.delete(:user_id)
        redirect_to sign_in_path, notice: 'Successfully Signed Out'
        
    end
    
    
    end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    
    def welcome
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    
    @user = User.all
    
  end

  def new
    @user = User.new
    
  end

  def create
    
    @user = User.new(user_params)
    
    if @user.save
      Usermailer.welcome_email(@user).deliver
     
      redirect_to user_path(id: @user.id), notice: 'Succussfully Signed Up'
    else 
      render :new
  end
end


  def show
    
    @user = User.find(params[:id])
    
  end
  

  def edit
    
    @user = User.find(params[:id])
    
  end

  def update

 @user = User.find(params[:id])
    
    if @user.update_attributes(user_params)
      redirect_to user_path(id: @user.id), notice: 'Succesfully Updated'
    
  else
    
    render :edit
    
  end
  
  end

  def destroy
    
   @user = User.find(params[:id])
   
   if @user.destroy
      redirect_to users_path, notice: "Successfully deleted"
      
    else
      
      render :index
      
    end
  
  
  
  end
  
  def user_params
     params.require(:user).permit(:name, :email,  :password, :password_confirmation)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_user_helper.rb
module SessionUserHelper
    
    def user_logged_in
        
          if session[:user_id]
              true
            
           else
                 false
           end
    end 
    
    
    def current_user
    
         if user_logged_in
              User.find(session[:user_id])
              
          else
              nil
         end
        
    end
    
    
        
    end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "WHATIMEISIT", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav pull-right">
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "Register",   sign_up_path %></li>
            <li><%= link_to "Log in", sign_in_path %></li>
          </ul>
        </nav>
      </div>
    </header>

    </div>
  </body>
</html>

app/views/layouts/_header2.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "WHATIMEISIT", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "Home", root_path %></li>
     
        <% if user_logged_in %>
          <li><%= link_to "Users", user_path(current_user.id) %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account git<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to " Edit Profile", edit_user_path(current_user.id) %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
            <%= link_to 'Sign Out', sign_out_path(current_user.id), method: :delete %>
              </li>
            </ul>
          </li>
          
        <%else%>
          <li><%= link_to "Sign in", sign_in_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <% if !user_logged_in %>
  
  <%= render 'layouts/header' %>
  
  <% else %>
  <%= render 'layouts/header2' %>
   
  
  <% end %>

<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
 <% end -%>
 

    
<div class="container-fluid">
  <%= yield %>
</div>

</body>
</html>

app/views/session_user/_form.html.erb
<%= form_for :session do |f| %>
           
            <% if @user.errors.any? %>
               <div id="error_explanation">
                    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this post from being saved:</h2>
 
                        <ul>
                           <% @user.errors.full_messages.each do |msg| %>
                                 <li><%= msg %></li>
                          <% end %>
                        </ul>
                     </div>
<% end %>
                
                <div class ="row">
                  <div class="input-group col-xs-6">
                    <span class="input-group-addon "><%= f.label :email %></span>
                    <%= f.text_field :email, class: "form-control" %>
                </div>
            </div>
            

            
            
             <div class ="row">
                  <div class="input-group col-xs-6">
                    <span class="input-group-addon "><%= f.label :password %></span>
                    <%= f.password_field :password, class: "form-control" %>
                </div>
            </div>
            
       
            
           <div class ="row">
                  <div class="input-group col-xs-6">
                    <%= f.submit 'Login', class: "btn btn-default" %>
                </div>
            </div>
            
        <% end %>    

app/views/session_user/new.html.erb
  </br>
  </br>
  </br>
  </br>
 
<div class="jumbotron">
<center>
  <h1>User Sign In  </h1>
</br>
  </br>
           <%= render 'form' %> 
           
       </center>   
</div>

app/views/static_pages/welcome.html.erb
  </br>
  </br>
  </br>
  </br>

<div class="jumbotron">
<center>
  <h1>Welcome to Whatimeisit!</h1>
  <p>This is my First Ruby Application</p>

  <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
  </center>
</div>

app/views/users/_form.html.erb
<center>
<%= form_for @user do |f| %>
           
            <% if @user.errors.any? %>
               <div id="error_explanation">
                    <p><%= pluralize(@user.errors.count, "error") %> prohibited this post from being saved:</p>
 
                        <ul>
                           <% @user.errors.full_messages.each do |msg| %>
                                 <li><%= msg %></li>
                          <% end %>
                        </ul>
                     </div>
<% end %>
       </center>         
                <div class ="row">
                  <div class="input-group col-xs-6">
                    <span class="input-group-addon "><%= f.label :name %></span>
                    <%= f.text_field :name, class: "form-control" %>
                </div>
            </div>
            
               <div class ="row">
                  <div class="input-group col-xs-6">
                    <span class="input-group-addon "><%= f.label :email %></span>
                    <%= f.text_field :email, class: "form-control" %>
                </div>
            </div>
            
            
             <div class ="row">
                  <div class="input-group col-xs-6">
                    <span class="input-group-addon "><%= f.label :password %></span>
                    <%= f.password_field :password, class: "form-control" %>
                </div>
            </div>
            
             <div class ="row">
                  <div class="input-group col-xs-6">
                    <span class="input-group-addon"><%= f.label :password_confirmation %></span>
                    <%= f.password_field :password_confirmation, class: "form-control" %>
                </div>
            </div>
            
           <div class ="row">
                  <div class="input-group col-xs-6">
                    <%= f.submit 'Login' class: "btn btn-default" %>
                </div>
            </div>
            
        <% end %>    

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/edit.html.erb
  </br>
  </br>
  </br>
  </br>
 
<div class="jumbotron">
<center>
  <h1>Update Profile </h1>

    <div class="container"> 
</br>
  </br>
           <%= render 'form' %> 
           
       </center>    
     </div>    
</div>

app/views/users/index.html.erb
</br>
</br>

<h1><b>User List </h1></b>
<ul>
    
    <% @user.each do|user| %>
       <li>
       <span><%= link_to user.name, edit_user_path(id: user.id) %></span>
         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  
        <span> <%= link_to 'Delete', user_path(id: user.id), method: :delete, confirm: 'Are you sure want to delete' %> </span>
       </li>
    
    <% end %>
    
    
</ul>

app/views/users/new.html.erb
<div class="jumbotron">
<center>
  <h1>Register Now !</h1>

    <div class="container"> 

           <%= render 'form' %> 
           
           </center>
           
     </div>    
</div>

app/views/users/show.html.erb
  </br>
  </br> 
  <div class='col-xs-20 col-xs-offset-7'>
<h1><b>Welcome <%= @user.name %></h1></b>
<table>
    <tr>
        <td>
            Name:
        </td>
        <td>
            <%= @user.name %>
        </td>
    </tr>
   <tr>
        <td>
            Email:
        </td>
        <td>
            <%= @user.email %>
        </td>
    </tr>
</table>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>